### ISSUE TITLE
"mocha-junit-reporter" reporter blew up with error:

### ISSUE THREAD

**Issue by brentwg** [devops-recipes/basic-node#5]
Hi: my JS-fu is not strong, so sorry in advance. I was attempting to build this project - as per [Run a sample CI build](http://docs.shippable.com/getting-started/ci-sample/) and the build failed. This is the error that I received:

$MOD_LOC/mocha --recursive "$TESTS_LOC_DIR/**/*.spec.js" -R mocha-junit-reporter --reporter-options mochaFile=$TEST_RESULTS_DIR/testresults.xml 0s  
"mocha-junit-reporter" reporter blew up with error:
/root/src/github.com/brentwg/basic-node/node_modules/mocha-junit-reporter/node_modules/strip-ansi/index.js:2
const ansiRegex = require('ansi-regex');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/root/src/github.com/brentwg/basic-node/node_modules/mocha-junit-reporter/index.js:10:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Mocha.reporter (/root/src/github.com/brentwg/basic-node/node_modules/mocha/lib/mocha.js:153:21)
    at Object.<anonymous> (/root/src/github.com/brentwg/basic-node/node_modules/mocha/bin/_mocha:220:7)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
/root/src/github.com/brentwg/basic-node/node_modules/mocha/lib/mocha.js:174
      throw new Error('invalid reporter "' + reporter + '"');
            ^
Error: invalid reporter "mocha-junit-reporter"
    at Mocha.reporter (/root/src/github.com/brentwg/basic-node/node_modules/mocha/lib/mocha.js:174:13)
    at Object.<anonymous> (/root/src/github.com/brentwg/basic-node/node_modules/mocha/bin/_mocha:220:7)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

Not really sure where to begin. Please let me know, if you require any additional information.

**Comment by manishas** [comment]
Thanks for reporting this! We have fixed the issue.

**Comment by Aditya18Jain** [comment]
Still facing the same issue.
